<?php
//发送邮件相关配置
return[
    'EMAIL_SMTP'=>'smtp.qq.com',
    'EMAIL_ADDRESS'=>'987114247@qq.com',
    'EMAIL_LOGINNAME'=>'987114247@qq.com',
    'EMAIL_PASSWORD'=>'akkbandwzeiubfcb',
    'port'=>25
];